// <auto-generated />
using System;
using MesApi.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MesApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260304113638_AddLastUpdateAndModifiedTime")]
    partial class AddLastUpdateAndModifiedTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductType")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2026, 3, 1, 17, 36, 40, 406, DateTimeKind.Local).AddTicks(5541),
                            Description = "Phone product description",
                            LastUpdate = "",
                            Name = "Phone product",
                            ProductType = 0,
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2026, 3, 3, 7, 4, 7, 406, DateTimeKind.Local).AddTicks(5541),
                            Description = "Tablet product description",
                            LastUpdate = "",
                            Name = "Tablet product",
                            ProductType = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2026, 3, 1, 21, 7, 9, 406, DateTimeKind.Local).AddTicks(5541),
                            Description = "Smartwatch product description",
                            LastUpdate = "",
                            Name = "Smartwatch product",
                            ProductType = 2,
                            Status = 2
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2026, 3, 3, 0, 40, 12, 406, DateTimeKind.Local).AddTicks(5541),
                            Description = "Earbuds product description",
                            LastUpdate = "",
                            Name = "Earbuds product",
                            ProductType = 3,
                            Status = 4
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
